### ISSUE TITLE
coord_cartesian not producing any result

### ISSUE THREAD

**Issue by elainawaters** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#13]
Hi,
I have made my code and plot for the phosphorus data but the coord_cartesian section isn't changing anything (not scaling in) but also not producing any sort of error. My plot looks the same regardless of what numbers I put in.

**Comment by YananR** [comment]
Hello, I also used the `coord_cartesian()`,  and the same thing happened to me. If you just want the y-scale from 0 to 0.3, you need to use `filter()` to filter the data for the surface of the lake (i.e. depth = 0 m). Please check [this](https://github.com/UM-R-for-EnvSci-Registered-Student-2021/General_Discussion/issues/11#issue-1039831133). Hope this could be helpful.

**Comment by aura-diaz** [comment]
Hi, I used the `coord_cartesian()` and it seems to work fine. This is how i used it

```{r}
plot_2<- phosphorus_data %>%
  filter(sample_depth_m < 1) %>%                   # plot only surface data
  ggplot() +
  geom_violin(aes(....)) +
  geom_jitter(aes(....)) +
  labs(...) +
  coord_cartesian(ylim = c(0,0.35),expand = FALSE)   # i set the expand false so it doesn't add any expansion to the limits

```
Hope this help :)

**Comment by elainawaters** [comment]
hi!
I tried this yesterday evening and it produced no result, so this morning I retyped out everything and it worked. I can only guess that maybe I had a typo or something somewhere?
Thanks for your help!

**Comment by peperg** [comment]
@elainawaters, sorry i am late to the game! Glad to hear it all ended up working!

@YananR and @aura-diaz, as always, thanks for keeping and eye on the issues and helping out!
