### ISSUE TITLE
wk08_homework

### ISSUE THREAD

**Issue by YananR** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#15]
Hello,

I am not sure the data used for the the point plot. I plotted all the data points, but the example figure just has a few points. Do I need to do any filtration? I have uploaded my file, you can check it. @peperg 

Thank you.

**Comment by YananR** [comment]
I solved it, it should be only box plot.

**Comment by peperg** [comment]
@YananR, sorry that it took me a little bot of time to get to this, but i am glad you solved it! Let me know if you have any other questions.
