### ISSUE TITLE
Error message: Continuous x aesthetic -- did you forget aes(group=...)? 

### ISSUE THREAD

**Issue by ReiSHIBUE** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#16]
I received this error message when I tried to plot a figure;

"Continuous x aesthetic -- did you forget aes(group=...)? "

I think it means the variable I put is not discrete.

I made a plot, but box plot does not work well.
My plot only shows data from 2004 and doesn't show data from 2002, so I only see one box plot in each section.
Also, the legend only shows 2004 too.

As an argument, I used a variable that is a combined data of date and time (this goes to x).

The box plot of 2004 which I made is completely same as the reference, so I just want to plot the data of 2002.

Are there someone who have same problem or get that error message?

**Comment by nicoleloeb** [comment]
Hello! 

I didn't see that specific issue, but I think you could fix it by setting the year column as a factor (example: ```mutate(year = as.factor(year))```) before putting it into ```ggplot()```. You might be able to use a different column, but this worked for me! Hope that helps!

**Comment by ReiSHIBUE** [comment]
@nicoleloeb 
Thank you so much for your reply!!
Thanks to your suggestion, I succeeded to set the column as a factor, so the error message disappeared!
Thank you so much!!

**Comment by peperg** [comment]
@ReiSHIBUE , @nicoleloeb , sorry that it took me a little bit to get to this mesage. I can see that the issue seems resolved now, is that correct? Let me know if you still need guidance!

**Comment by ReiSHIBUE** [comment]
@peperg Thank you so much for your reply!
Yes! I resolved my problem thanks to @nicoleloeb !!
If I have another trouble, I will make new issue! Thank you very much!!
