### ISSUE TITLE
How to save my theme as a function

### ISSUE THREAD

**Issue by elainawaters** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#17]
Hello,
How do I save my theme as a function?
Thanks in advance!

**Comment by GeraldBeta** [comment]
Hi , try by using "function" and save the way you save scripts

theme_elainwaters <- function(base_size = 1,
                                                 base .............)

**Comment by elainawaters** [comment]
Thanks Gerald!

**Comment by peperg** [comment]
Hi!

Sorry @elainawaters and @GeraldBeta for getting to this a bit late. I am glad you seem to have figured it out. If in doubt, feel free to replicate the `theme_pepe_full.R` file that i provide with the class notes, that should have all the info you need!
