### ISSUE TITLE
Tidy data-excel column name issue

### ISSUE THREAD

**Issue by YananR** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#2]
If I have several excel tables (in different excel files) that use the same column name (e.g., pH), but these pHs are not the same thing (e.g., pH of influent or effluent), should I change the name for each, like pH_Inf in file 1, and pH_Eff in file 2? Or this will not cause any problems when I process my data later on. Thank you! @peperg

**Comment by peperg** [comment]
@YananR, good question.

My recomendation would be, as noted in class, to "design trouble away". If these are pH values measured in diferent matrices that will end up in the same table, then ideally you would name your variables accordingly to make sure that this distinction is clear. So your example of "ph_inf" and "ph_eff" (note the lower case!) woud be my prefered choice. I know i said that keeping variable names short is always good, but it is more importnat to make your variables clearly recognizable.

We will see when we get to the joins that you can tell R which is your Key variable, so if there are other variables that share a name, the join process will just change their name so they dont overlap (e.g. ph.x and ph.y). That prevents a big problem from hapening, but at some point you are still going to need to change those variable names, so you might as well code them to a more descriptive name from the begining.

I hope that helps!

**Comment by YananR** [comment]
@peperg Thank you. It helps a lot. One more question, do I need to use lower case anywhere in excel and file name? How about the upper case letter? I started to tidy my data, probably more questions later on.

**Comment by peperg** [comment]
@YananR, ideally you want to follow the suggestions in the [tidyverse style guide](https://style.tidyverse.org/) from the begining. There they recomend to use *snake case* (e.g. example_variable) all lower case and words separated by undercores. If you are starting from zero, i would recomend you use this aproach for variable names. If not, we will soon see in class a nice tool that can help you formating all variable names into that style later on as part of your work-flow.

Pepe
