### ISSUE TITLE
home work 05

### ISSUE THREAD

**Issue by YananR** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#3]
exercise 1, point 3 "Ensure no data is missing from this summary table". I think you just want us to use the group code, and we need to show the monthly summary table with new variables, not all data from the original data set. Do I misunderstand your requirement? @peperg

**Comment by peperg** [comment]
@YananR, yes, you are correct. The new summary table should only have the summary values, not the original data. Sorry the wording of that section is a bit confusing. what i meant was. a **hint** for you guys to remember the `rm.na = TRUE` part.

I hope this makes sense!

**Comment by YananR** [comment]
@peperg, Got it. Thank you.
