### ISSUE TITLE
Week 05 hw (exercise 2)

### ISSUE THREAD

**Issue by fowziaahmed** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#4]
Hello!
In exercise 2, it was written to create a new object containing only columns station, month, and monthly max. Should I input weather data again and extract these columns? or do I need to create columns with fake data? @peperg or anyone can help?

**Comment by aura-diaz** [comment]
@fowziaahmed we have to use the data file that created in exercise 1

**Comment by fowziaahmed** [comment]
Thanks a lot @aura-diaz

**Comment by peperg** [comment]
Hello all! @aura-diaz thank you for lending a hand, that is exactly what i was asking for. @fowziaahmed let me know if you still need guidance.

Awesome work using the issues!

**Comment by fowziaahmed** [comment]
Thanks @peperg, problem solved :D
