### ISSUE TITLE
summary code is only giving one value

### ISSUE THREAD

**Issue by elainawaters** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#5]
I'm pretty sure the issue is my code, but I'm not sure how to get a mean for each month and not just a total max, min, and mean temp

**Comment by aura-diaz** [comment]
@elainawaters you have to group the data by month and then find the max, min, and mean temperature per month

**Comment by peperg** [comment]
@aura-diaz, thank you again for being there to help, that is exactly the recomended way. @elainawaters did it end up working for you?

**Comment by elainawaters** [comment]
Yes, thank you @aura-diaz ! After reviewing my notes and code for how to do that I got it to work.
