### ISSUE TITLE
wk06-hw

### ISSUE THREAD

**Issue by YananR** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#7]
For the box plot, my data dots distribution is not the same as the reference. I tried different widths, but it seems it never gets the same trend. Is my code wrong with `geom_jitter()`, or `ditch_data` should be analyzed first? @peperg

**Comment by peperg** [comment]
@YananR, i can check once you push the exercise, but i am pretty sure it is ok. The exact location of the jitter points is randomized, so unless you set the seed (like i showed you in class) every time you run the code you will get a slightly different plot. Try and see if this is what is happening.

Also, feel free to push to GitHub through the week, i dont "grade" the homework, they are meant for you to practice and for me to ensure that people are up-to-date, so easier for me to check on things like this if its up, even if not finished. I will only check for completenesss after the deadline. The GitHub repor is free for you to use as a dropbox if you want!

Pepe

**Comment by YananR** [comment]
@peperg Thank you for your explanation. Yes, I tried, the distribution changed when I run codes.
I pushed my homework.

**Comment by ReiSHIBUE** [comment]
@YananR @peperg 
Thank you so much for asking this question!
I also think about same thing and every time I tried to change width (tried to put 0.2, 0.5 and even 0.05 etc), my image was not be identical to the reference image.

So your question solved my question too! Thank you very much!
