### ISSUE TITLE
Combining Plots Error

### ISSUE THREAD

**Issue by jkozak180** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#9]
Hi everyone, 

I am at my wits' end trying to combine the two separate plots for chlorophyll and phosphorus using the `patchwork` package. I was wondering if anyone had successfully solved/knew how to solve this error;
`Error in Ops.data.frame(chlorophyll_a_conc, total_phos_profiles) : '+' only defined for equally-sized data frames`

I cannot get these two figures to merge. I used both `+`, `/` symbols and changed `ncol` to `nrow=2` , along with many, many other things but nothing seems to work.

**Comment by peperg** [comment]
@jkozak180, hard to tell what is happening. The error message makes it sound like you are trying to apply the "+" to datasets instead of plot objects. Maybe commit and push what you have and i will take a look at you code.

**Comment by ReiSHIBUE** [comment]
@jkozak180 
Hi!
I suppose you may not input your plots as an object.
If you put a name of two ggplot images on console, I guess you may get 2 tibble's data.
It means your 2 plots is not inputted as an object and its still data frame (tibble).
If it doesn't help you, I am sorry.

**Comment by jkozak180** [comment]
No! This was all extremely helpful!! 
I just assigned a name to the plot to make it an object and that worked! 

Thank you so much!!! @peperg @ReiSHIBUE

**Comment by ReiSHIBUE** [comment]
@jkozak180  I'm glad to hear that! I also received same error message, so I had same problem too!

**Comment by peperg** [comment]
Great work on figuringthis out everyone!
